# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" 
    directory: "/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-background-processor" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-block-sync" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-invoice" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-net"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-net-tokio"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning-persister"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo" 
    directory: "/lightning"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "daily"
