// This file is Copyright its original authors, visible in version control
// history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE
// or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// You may not use this file except in accordance with one or both of these
// licenses.

//! Events generated by the LSPS5 service and client

use crate::lsps0::ser::LSPSRequestId;
use crate::lsps5::msgs::WebhookNotificationMethod;
use bitcoin::secp256k1::PublicKey;

/// Events emitted by the LSPS5 webhook service (LSP side)
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LSPS5ServiceEvent {
	/// A webhook was registered by a client
	WebhookRegistered {
		/// Client node ID
		client: PublicKey,
		/// App name
		app_name: String,
		/// Webhook URL
		url: String,
		/// Request ID for tracking
		request_id: LSPSRequestId,
		/// Whether this was a new registration or an update to existing one
		no_change: bool,
	},

	/// Webhooks were listed for a client
	WebhooksListed {
		/// Client node ID
		client: PublicKey,
		/// App names with registered webhooks
		app_names: Vec<String>,
		/// Maximum number of webhooks allowed
		max_webhooks: u32,
		/// Request ID for tracking
		request_id: LSPSRequestId,
	},

	/// A webhook was removed
	WebhookRemoved {
		/// Client node ID
		client: PublicKey,
		/// App name
		app_name: String,
		/// Request ID for tracking
		request_id: LSPSRequestId,
	},

	/// A notification was sent to a webhook
	WebhookNotificationSent {
		/// Client node ID
		client: PublicKey,
		/// App name
		app_name: String,
		/// Webhook URL
		url: String,
		/// Notification method
		method: WebhookNotificationMethod,
		/// Timestamp of the notification
		timestamp: String,
		/// Signature of the notification
		signature: String,
	},
}

/// Events emitted by the LSPS5 webhook client (Lightning node side)
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LSPS5ClientEvent {
	/// A webhook was successfully registered with the LSP
	WebhookRegistered {
		/// LSP node ID
		lsp: PublicKey,
		/// App name
		app_name: String,
		/// Webhook URL
		url: String,
		/// Number of webhooks now registered
		num_webhooks: u32,
		/// Maximum number of webhooks allowed
		max_webhooks: u32,
		/// Whether this was a new registration or an update to existing one
		no_change: bool,
	},

	/// Failed to register a webhook with the LSP
	WebhookRegistrationFailed {
		/// LSP node ID
		lsp: PublicKey,
		/// App name
		app_name: String,
		/// Webhook URL
		url: String,
		/// Error code
		error_code: i32,
		/// Error message
		error_message: String,
	},

	/// Received list of registered webhooks from the LSP
	WebhooksListed {
		/// LSP node ID
		lsp: PublicKey,
		/// App names with registered webhooks
		app_names: Vec<String>,
		/// Maximum number of webhooks allowed
		max_webhooks: u32,
	},

	/// Failed to list webhooks
	WebhooksListFailed {
		/// LSP node ID
		lsp: PublicKey,
		/// Error code
		error_code: i32,
		/// Error message
		error_message: String,
	},

	/// A webhook was successfully removed
	WebhookRemoved {
		/// LSP node ID
		lsp: PublicKey,
		/// App name
		app_name: String,
	},

	/// Failed to remove a webhook
	WebhookRemovalFailed {
		/// LSP node ID
		lsp: PublicKey,
		/// App name
		app_name: String,
		/// Error code
		error_code: i32,
		/// Error message
		error_message: String,
	},

	/// A webhook notification was received from the LSP
	WebhookNotificationReceived {
		/// LSP node ID
		lsp: PublicKey,
		/// The notification method that was received
		method: WebhookNotificationMethod,
		/// Timestamp of the notification
		timestamp: String,
		/// Whether the signature verification succeeded
		signature_valid: bool,
		/// The notification parameters (might be empty depending on method)
		parameters: Option<WebhookNotificationParams>,
	},
}

/// Parameters for different webhook notification methods
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WebhookNotificationParams {
	/// Parameters for lsps5.expiry_soon notification
	ExpirySoon {
		/// Block height when timeout occurs
		timeout: u32,
	},
	/// For future extensions of other notification types that might have parameters
	Other,
}
